// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: api/ocp-classroom-api/ocp-classroom-api.proto

/*
Package ocp_classroom_api is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package ocp_classroom_api

import (
	"context"
	"io"
	"net/http"

	"github.com/golang/protobuf/descriptor"
	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = descriptor.ForMessage
var _ = metadata.Join

var (
	filter_OcpClassroomApi_DescribeClassroom_0 = &utilities.DoubleArray{Encoding: map[string]int{"classroom_id": 0}, Base: []int{1, 1, 0}, Check: []int{0, 1, 2}}
)

func request_OcpClassroomApi_DescribeClassroom_0(ctx context.Context, marshaler runtime.Marshaler, client OcpClassroomApiClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DescribeClassroomRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["classroom_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "classroom_id")
	}

	protoReq.ClassroomId, err = runtime.Uint64(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "classroom_id", err)
	}

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_OcpClassroomApi_DescribeClassroom_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.DescribeClassroom(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_OcpClassroomApi_DescribeClassroom_0(ctx context.Context, marshaler runtime.Marshaler, server OcpClassroomApiServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DescribeClassroomRequest
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["classroom_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "classroom_id")
	}

	protoReq.ClassroomId, err = runtime.Uint64(val)

	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "classroom_id", err)
	}

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_OcpClassroomApi_DescribeClassroom_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.DescribeClassroom(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterOcpClassroomApiHandlerServer registers the http handlers for service OcpClassroomApi to "mux".
// UnaryRPC     :call OcpClassroomApiServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterOcpClassroomApiHandlerFromEndpoint instead.
func RegisterOcpClassroomApiHandlerServer(ctx context.Context, mux *runtime.ServeMux, server OcpClassroomApiServer) error {

	mux.Handle("POST", pattern_OcpClassroomApi_DescribeClassroom_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_OcpClassroomApi_DescribeClassroom_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_OcpClassroomApi_DescribeClassroom_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterOcpClassroomApiHandlerFromEndpoint is same as RegisterOcpClassroomApiHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterOcpClassroomApiHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterOcpClassroomApiHandler(ctx, mux, conn)
}

// RegisterOcpClassroomApiHandler registers the http handlers for service OcpClassroomApi to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterOcpClassroomApiHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterOcpClassroomApiHandlerClient(ctx, mux, NewOcpClassroomApiClient(conn))
}

// RegisterOcpClassroomApiHandlerClient registers the http handlers for service OcpClassroomApi
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "OcpClassroomApiClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "OcpClassroomApiClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "OcpClassroomApiClient" to call the correct interceptors.
func RegisterOcpClassroomApiHandlerClient(ctx context.Context, mux *runtime.ServeMux, client OcpClassroomApiClient) error {

	mux.Handle("POST", pattern_OcpClassroomApi_DescribeClassroom_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_OcpClassroomApi_DescribeClassroom_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_OcpClassroomApi_DescribeClassroom_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_OcpClassroomApi_DescribeClassroom_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1}, []string{"classrooms", "classroom_id"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_OcpClassroomApi_DescribeClassroom_0 = runtime.ForwardResponseMessage
)
